# Generated by Django 4.0.4 on 2022-06-12 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compro', '0008_alter_stakeholder_name'),
        ('month', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ikami',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.IntegerField()),
                ('tata_kelola', models.IntegerField()),
                ('pengelolaan_risiko', models.IntegerField()),
                ('kerangka_kerja', models.IntegerField()),
                ('pengelolaan_aset', models.IntegerField()),
                ('teknologi_keamanan', models.IntegerField()),
                ('keterlibatan_pihak_ketiga', models.IntegerField(blank=True, null=True)),
                ('layanan_infrastruktur_awan', models.IntegerField(blank=True, null=True)),
                ('data_pribadi', models.IntegerField(blank=True, null=True)),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='month.month')),
                ('stakeholder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compro.stakeholder')),
            ],
        ),
    ]
