# Generated by Django 4.0.4 on 2022-05-24 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compro', '0004_stakeholder_slug'),
        ('month', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Csm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.IntegerField()),
                ('kesadaran', models.FloatField()),
                ('audit', models.FloatField()),
                ('kontrol', models.FloatField()),
                ('pemenuhan', models.FloatField()),
                ('kebijakan', models.FloatField()),
                ('proses', models.FloatField()),
                ('manajemen_aset', models.FloatField()),
                ('inventaris', models.FloatField()),
                ('manajemen_risiko', models.FloatField()),
                ('prioritas', models.FloatField()),
                ('pelaporan_identifikasi', models.FloatField()),
                ('klasifikasi', models.FloatField()),
                ('jaringan', models.FloatField()),
                ('aplikasi', models.FloatField()),
                ('pengguna', models.FloatField()),
                ('manajemen_identitas', models.FloatField()),
                ('cloud', models.FloatField()),
                ('data', models.FloatField()),
                ('perubahan', models.FloatField()),
                ('monitor', models.FloatField()),
                ('peringatan', models.FloatField()),
                ('pemberitahuan', models.FloatField()),
                ('intelijen', models.FloatField()),
                ('pelaporan_deteksi', models.FloatField()),
                ('penahanan', models.FloatField()),
                ('penanggulanan', models.FloatField()),
                ('pemulihan', models.FloatField()),
                ('kegiatan_pasca', models.FloatField()),
                ('pelaporan_respon', models.FloatField()),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='month.month')),
                ('stakeholder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compro.stakeholder')),
            ],
        ),
    ]
