# Generated by Django 4.0.4 on 2022-06-08 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compro', '0004_stakeholder_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sistemelektronik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nama', models.CharField(max_length=255)),
                ('spesifikasi', models.TextField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=255, null=True)),
                ('unit_pengelola', models.CharField(blank=True, max_length=255, null=True)),
                ('stakeholder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compro.stakeholder')),
            ],
        ),
        migrations.CreateModel(
            name='Prosedur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nama', models.CharField(max_length=255)),
                ('nomer', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('RL', 'Release'), ('PB', 'Publication'), ('DR', 'Draft')], default='DR', max_length=2)),
                ('tahun', models.CharField(blank=True, max_length=4, null=True)),
                ('stakeholder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compro.stakeholder')),
            ],
        ),
        migrations.CreateModel(
            name='Narahubung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nama', models.CharField(max_length=255)),
                ('jabatan', models.CharField(blank=True, max_length=255, null=True)),
                ('unit_kerja', models.CharField(blank=True, max_length=255, null=True)),
                ('landing_page', models.CharField(max_length=255)),
                ('lokasi', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(default='info@corporate.com', max_length=255)),
                ('telepon', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('alamat', models.TextField(blank=True, null=True)),
                ('kode_pos', models.CharField(blank=True, max_length=255, null=True)),
                ('stakeholder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compro.stakeholder')),
            ],
        ),
        migrations.CreateModel(
            name='Csirt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nama', models.CharField(max_length=255)),
                ('unit_kerja', models.CharField(blank=True, max_length=255, null=True)),
                ('kompetensi', models.TextField(blank=True, null=True)),
                ('sertifikat', models.TextField(blank=True, null=True)),
                ('stakeholder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compro.stakeholder')),
            ],
        ),
    ]
