# Generated by Django 4.0.4 on 2022-06-18 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0001_initial'),
        ('compro', '0008_alter_stakeholder_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListWorkshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(blank=True, choices=[('PS', 'Peserta'), ('NS', 'Narasumber')], max_length=2, null=True)),
                ('sdm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='compro.sdm')),
                ('stakeholder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compro.stakeholder')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshop.workshop')),
            ],
        ),
    ]
