# Generated by Django 4.0.4 on 2022-05-03 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stakeholder',
            name='email',
            field=models.EmailField(default='info@corporate.com', max_length=255),
        ),
        migrations.AlterField(
            model_name='stakeholder',
            name='info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
