# Generated by Django 4.0.4 on 2022-05-03 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compro', '0003_stakeholder_created_at_stakeholder_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='stakeholder',
            name='slug',
            field=models.SlugField(blank=True, editable=False),
        ),
    ]
