# Generated by Django 4.0.4 on 2022-06-12 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compro', '0007_sdm_remove_narahubung_stakeholder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stakeholder',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
