# Generated by Django 4.0.4 on 2022-09-16 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compro', '0009_listworkshop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stakeholder',
            name='field',
            field=models.CharField(choices=[('IN', 'Industri'), ('KN', 'Konstruksi'), ('KM', 'Kamsiber')], max_length=5),
        ),
    ]
