# Generated by Django 4.0.4 on 2022-09-17 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compro', '0010_alter_stakeholder_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='stakeholder',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='stakeholder_logo'),
        ),
    ]
