# Generated by Django 4.0.4 on 2022-09-17 12:10

import compro.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compro', '0011_stakeholder_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stakeholder',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='stakeholder_logo', validators=[compro.validators.validate_image]),
        ),
    ]
