# Generated by Django 4.0.4 on 2022-09-17 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compro', '0012_alter_stakeholder_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stakeholder',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='stakeholder_logo'),
        ),
    ]
