# Generated by Django 4.1.1 on 2022-10-06 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compro', '0015_listworkshop_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listworkshop',
            name='sdm',
        ),
        migrations.AddField(
            model_name='listworkshop',
            name='sdm',
            field=models.ManyToManyField(to='compro.sdm'),
        ),
    ]
