# Generated by Django 4.0.4 on 2022-09-17 12:11

from django.db import migrations, models
import tmpi.validators


class Migration(migrations.Migration):

    dependencies = [
        ('tmpi', '0002_alter_tmpi_file_tmpi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmpi',
            name='file_tmpi',
            field=models.FileField(blank=True, null=True, upload_to='tmpi/%Y/%m/%d', validators=[tmpi.validators.validate_excel_file, tmpi.validators.validate_extension]),
        ),
    ]
