# Generated by Django 4.0.4 on 2022-09-17 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmpi', '0003_alter_tmpi_file_tmpi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmpi',
            name='file_tmpi',
            field=models.FileField(blank=True, null=True, upload_to='tmpi/%Y/%m/%d'),
        ),
    ]
