# Generated by Django 4.1.1 on 2022-10-04 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmpi', '0005_alter_tmpi_file_tmpi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmpi',
            name='file_tmpi',
            field=models.FileField(blank=True, null=True, upload_to='ttis_evaluasi'),
        ),
    ]
