# Generated by Django 4.0.4 on 2022-06-12 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nama', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, editable=False)),
                ('tanggal', models.DateTimeField(blank=True, null=True)),
                ('lokasi', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
