# Generated by Django 4.1.1 on 2022-10-04 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='deskripsi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workshop',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='workshop'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='level',
            field=models.CharField(blank=True, choices=[('bsc', 'Basic'), ('int', 'Intermediate'), ('adv', 'Advance')], max_length=3, null=True),
        ),
    ]
