# Generated by Django 4.1.1 on 2022-10-04 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0002_workshop_deskripsi_workshop_image_workshop_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshop',
            name='level',
        ),
    ]
