# Generated by Django 4.1.1 on 2022-10-07 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0003_remove_workshop_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='jenis',
            field=models.CharField(blank=True, choices=[('WS', 'Workshop'), ('RP', 'Rapat')], max_length=2, null=True),
        ),
    ]
