# Generated by Django 4.0.4 on 2022-09-24 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workshop', '0001_initial'),
        ('tmpi', '0005_alter_tmpi_file_tmpi'),
        ('compro', '0014_stakeholder_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perencanaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('draft_sk', models.IntegerField(choices=[(1, 'Yes'), (0, 'No')], default=0)),
                ('no_draft_sk', models.CharField(blank=True, max_length=250, null=True)),
                ('tgl_draft_sk', models.DateTimeField(blank=True, null=True)),
                ('draft_rfc', models.IntegerField(choices=[(1, 'Yes'), (0, 'No')], default=0)),
                ('no_draft_rfc', models.CharField(blank=True, max_length=250, null=True)),
                ('tgl_draft_rfc', models.DateTimeField(blank=True, null=True)),
                ('draft_sumber_daya', models.IntegerField(choices=[(1, 'Yes'), (0, 'No')], default=0)),
                ('no_draft_sumber_daya', models.CharField(blank=True, max_length=250, null=True)),
                ('tgl_draft_sumber_daya', models.DateTimeField(blank=True, null=True)),
                ('stakeholder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compro.stakeholder')),
            ],
        ),
        migrations.CreateModel(
            name='Penguatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(blank=True, choices=[('bsc', 'Basic'), ('int', 'Intermediate'), ('adv', 'Advance')], max_length=3, null=True)),
                ('stakeholder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compro.stakeholder')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshop.workshop')),
            ],
        ),
        migrations.CreateModel(
            name='Penerapan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doc_sk', models.IntegerField(choices=[(1, 'Yes'), (0, 'No')], default=0)),
                ('no_doc_sk', models.CharField(blank=True, max_length=250, null=True)),
                ('tgl_doc_sk', models.DateTimeField(blank=True, null=True)),
                ('doc_rfc', models.IntegerField(choices=[(1, 'Yes'), (0, 'No')], default=0)),
                ('no_doc_rfc', models.CharField(blank=True, max_length=250, null=True)),
                ('tgl_doc_rfc', models.DateTimeField(blank=True, null=True)),
                ('doc_sumber_daya', models.IntegerField(choices=[(1, 'Yes'), (0, 'No')], default=0)),
                ('no_doc_sumber_daya', models.CharField(blank=True, max_length=250, null=True)),
                ('tgl_doc_sumber_daya', models.DateTimeField(blank=True, null=True)),
                ('portal_csirt', models.IntegerField(choices=[(1, 'Yes'), (0, 'No')])),
                ('stakeholder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compro.stakeholder')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(1, 'Yes'), (0, 'No')], default=0)),
                ('stakeholder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compro.stakeholder')),
                ('tmpi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tmpi.tmpi')),
            ],
        ),
        migrations.CreateModel(
            name='Edukasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sosialisasi', models.IntegerField(choices=[(1, 'Yes'), (0, 'No')], default=0)),
                ('tempat', models.CharField(blank=True, max_length=250, null=True)),
                ('tanggal', models.DateTimeField(blank=True, null=True)),
                ('stakeholder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compro.stakeholder')),
            ],
        ),
    ]
