# Generated by Django 4.0.4 on 2022-09-26 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tahap_csirt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='edukasi',
            name='file_edukasi',
            field=models.FileField(blank=True, null=True, upload_to='ttis_edukasi'),
        ),
    ]
