# Generated by Django 4.0.4 on 2022-09-29 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tahap_csirt', '0002_edukasi_file_edukasi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edukasi',
            name='file_edukasi',
        ),
        migrations.AddField(
            model_name='evaluasi',
            name='file_tmpi',
            field=models.FileField(blank=True, null=True, upload_to='ttis_evaluasi'),
        ),
        migrations.AddField(
            model_name='penerapan',
            name='file_rfc',
            field=models.FileField(blank=True, null=True, upload_to='ttis_penerapan'),
        ),
        migrations.AddField(
            model_name='penerapan',
            name='file_sk',
            field=models.FileField(blank=True, null=True, upload_to='ttis_penerapan'),
        ),
        migrations.AddField(
            model_name='penerapan',
            name='file_sumber_daya',
            field=models.FileField(blank=True, null=True, upload_to='ttis_penerapan'),
        ),
    ]
