# Generated by Django 4.0.4 on 2022-09-29 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tahap_csirt', '0003_remove_edukasi_file_edukasi_evaluasi_file_tmpi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='penerapan',
            name='portal_csirt_url',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
