# Generated by Django 4.1.1 on 2022-10-04 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compro', '0014_stakeholder_pic'),
        ('tahap_csirt', '0004_penerapan_portal_csirt_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edukasi',
            name='id',
        ),
        migrations.RemoveField(
            model_name='evaluasi',
            name='file_tmpi',
        ),
        migrations.RemoveField(
            model_name='evaluasi',
            name='id',
        ),
        migrations.RemoveField(
            model_name='penerapan',
            name='id',
        ),
        migrations.RemoveField(
            model_name='penguatan',
            name='id',
        ),
        migrations.RemoveField(
            model_name='penguatan',
            name='workshop',
        ),
        migrations.RemoveField(
            model_name='perencanaan',
            name='id',
        ),
        migrations.AlterField(
            model_name='edukasi',
            name='stakeholder',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='compro.stakeholder'),
        ),
        migrations.AlterField(
            model_name='evaluasi',
            name='stakeholder',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='compro.stakeholder'),
        ),
        migrations.AlterField(
            model_name='penerapan',
            name='stakeholder',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='compro.stakeholder'),
        ),
        migrations.AlterField(
            model_name='penguatan',
            name='stakeholder',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='compro.stakeholder'),
        ),
        migrations.AlterField(
            model_name='penguatan',
            name='status',
            field=models.IntegerField(choices=[(1, 'Yes'), (0, 'No')], default=0),
        ),
        migrations.AlterField(
            model_name='perencanaan',
            name='stakeholder',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='compro.stakeholder'),
        ),
    ]
