# Generated by Django 4.1.1 on 2022-10-04 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tahap_csirt', '0005_remove_edukasi_id_remove_evaluasi_file_tmpi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='penerapan',
            name='doc_registrasi',
            field=models.IntegerField(choices=[(1, 'Yes'), (0, 'No')], default=0),
        ),
        migrations.AddField(
            model_name='penerapan',
            name='file_registrasi',
            field=models.FileField(blank=True, null=True, upload_to='ttis_penerapan'),
        ),
        migrations.AddField(
            model_name='penerapan',
            name='no_doc_registrasi',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='penerapan',
            name='tgl_doc_registrasi',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
