# Generated by Django 4.0.4 on 2022-09-29 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phrasalword', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phrasalword',
            name='passphrase',
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
    ]
