# Generated by Django 4.1.1 on 2022-10-03 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phrasalword', '0002_alter_phrasalword_passphrase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phrasalword',
            name='passphrase',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
