# Generated by Django 4.1.1 on 2022-10-03 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phrasalword', '0003_alter_phrasalword_passphrase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phrasalword',
            name='passphrase',
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
    ]
