# Generated by Django 4.0.4 on 2022-05-24 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('month', '0001_initial'),
        ('compro', '0004_stakeholder_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Se',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.IntegerField()),
                ('indeks_nilai', models.FloatField(blank=True)),
                ('indeks_ket', models.CharField(blank=True, max_length=255)),
                ('sistem', models.TextField()),
                ('keterangan', models.TextField()),
                ('month', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='month.month')),
                ('stakeholder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compro.stakeholder')),
            ],
        ),
    ]
